/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SprintAnalysisRouteImport } from './routes/sprint-analysis'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CapacityRouteImport } from './routes/capacity'
import { Route as BrdRouteImport } from './routes/brd'
import { Route as IndexRouteImport } from './routes/index'

const SprintAnalysisRoute = SprintAnalysisRouteImport.update({
  id: '/sprint-analysis',
  path: '/sprint-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityRoute = CapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const BrdRoute = BrdRouteImport.update({
  id: '/brd',
  path: '/brd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brd': typeof BrdRoute
  '/capacity': typeof CapacityRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/sprint-analysis': typeof SprintAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brd': typeof BrdRoute
  '/capacity': typeof CapacityRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/sprint-analysis': typeof SprintAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brd': typeof BrdRoute
  '/capacity': typeof CapacityRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/sprint-analysis': typeof SprintAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brd'
    | '/capacity'
    | '/chat'
    | '/compare'
    | '/sprint-analysis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brd' | '/capacity' | '/chat' | '/compare' | '/sprint-analysis'
  id:
    | '__root__'
    | '/'
    | '/brd'
    | '/capacity'
    | '/chat'
    | '/compare'
    | '/sprint-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrdRoute: typeof BrdRoute
  CapacityRoute: typeof CapacityRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  SprintAnalysisRoute: typeof SprintAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sprint-analysis': {
      id: '/sprint-analysis'
      path: '/sprint-analysis'
      fullPath: '/sprint-analysis'
      preLoaderRoute: typeof SprintAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity': {
      id: '/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof CapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brd': {
      id: '/brd'
      path: '/brd'
      fullPath: '/brd'
      preLoaderRoute: typeof BrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrdRoute: BrdRoute,
  CapacityRoute: CapacityRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  SprintAnalysisRoute: SprintAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
